name: Shell Lint

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup shellcheck
        uses: ludeeus/action-shellcheck@2.0.0

      - name: Setup shfmt
        uses: mfinelli/setup-shfmt@v3

      - name: Show versions
        run: |
          shellcheck --version
          shfmt --version

      - name: Run shellcheck
        run: shellcheck -x install.sh

      - name: Run shfmt check
        run: shfmt -d -i 2 -ci -bn install.sh
